# Generated by Django 4.0 on 2023-03-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateInput', models.DateField()),
                ('id_project', models.TextField()),
                ('name_project', models.TextField()),
                ('detail', models.TextField()),
                ('total', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('detail', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
